title: AuriOS Docs
description: Official documentation for the AuriOS project.
author: Auri-OS
lang: en
baseurl: ""
url: ""

repo_url: https://github.com/auri-os/aurios

collections:
  docs:
    output: true
    permalink: /:path/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  toc_levels: 2..3

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: doc

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - .github
  - start.sh
